name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        go-version: [~1.14, ~1.13, ~1.12, ~1.11]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get install potrace
            cd ./vendor/gocv.io/x/gocv && make install

      - name: Install MacOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install potrace
          brew install opencv@3

      - name: Build Project
        run: |
          sudo ./build.sh -c -d